[package]
name = "sharding"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds = { path = "../ds" }

enum_dispatch = "*"
rust-crypto = "0.2.36"
log = "0.4.14"


