[package]
name = "context"
version = "0.1.0"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#log = { path = "../log" }

clap = "3.0.0-beta.2"
url = "2.2.2"
tokio = { version = "1.11.0", features = ["fs"] }
log = "0.4.14"

[features]
listen_all = []
