[package]
name = "discovery"
version = "0.1.0"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#log = { path = "../log" }
ds = { path = "../ds" }
protocol = { path = "../protocol" }

log = "0.4.14"
url = "2.2.2"
async-trait = "0.1.51"
enum_dispatch = "0.3.7"

#for http request and json parse
reqwest = {version = "0.11.4", features = ["json"]}
tokio = {version = "1.12.0", features = ["fs"]}
json = "0.12.4"

#for deserialize
serde = { version = "1.0.126", features = ["derive"] }
serde_derive = "1.0.126"
serde_yaml = "0.8.17"
serde_json = "1.0.65"
rand = "0.8.4"
futures = "0.3.16"
crossbeam-channel = "0.5.1"
async-recursion = "0.2"
merge-yaml-hash = "0.2.0"
