[package]
name = "agent"
version = "BREEZE_VERSION_PLACE_HOLDER"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
context = { path = "../context" }
net = { path = "../net"}
protocol = { path = "../protocol" }
endpoint = { path = "../endpoint" }
discovery = { path = "../discovery" }
elog = { path = "../log", package = "log" }
stream = { path = "../stream" }
metrics = { path = "../metrics" }

log = "0.4.14"
tokio = {version = "1.10.0", features = ["rt", "net", "rt-multi-thread", "time", "macros"]}
