[package]
name = "agent"
version = "0.0.1"
authors = ["icy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
context = { path = "../context" }
sharding = { path = "../sharding" }
net = { path = "../net"}
protocol = { path = "../protocol" }
endpoint = { path = "../endpoint" }
discovery = { path = "../discovery" }
log = { path = "../log" }
stream = { path = "../stream" }
metrics = { path = "../metrics" }
rt = { path = "../rt" }
ds = { path = "../ds" }
api = { path = "../api" }

backtrace = "0.3.63"
lazy_static = "1.4.0"

tokio = { version = "1.21.1", features = ["rt", "net", "rt-multi-thread", "time", "macros"]}
mimalloc = { version = "*", default-features = false }
cfg-if = "*"
once_cell = "*"

rlimit = "0.3.0"

# rocket for restful api
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_async_compression = "0.1.0"

[features]
default = ["prometheus"]
http = []
console-api = ["http"]
graphite = []
prometheus = ["http"]
