[package]
name = "ds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { path = "../log" }
tokio = {version = "1.20.1", features = ["rt", "net", "rt-multi-thread", "time", "macros"]}
mimalloc = { version = "*", default-features = false }

byteorder = "1.4.3"
rand = "0.8.4"
cache_line_size = "1.0.0"
crossbeam-queue = "0.3.2"
crossbeam-channel = "0.5.1"
cfg-if = "1"
futures = "0.3.17"
atomic-waker = "*"
backtrace = "0.3.63"
