[package]
name = "ds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#log = { path = "../log" }

byteorder = "1.4.3"
rand = "0.8.4"
cache_line_size = "1.0.0"
log = "0.4.14"
crossbeam-queue = "0.3.2"
cfg-if = "1"

[features]
default = ["single-thread"]
single-thread = []

