name: CI

on:
  push:
    branches: ["dev", "dev_ci"]
  pull_request:
    branches: ["dev", "dev_ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare vintage_mc_redis
        run: docker run  -d    -v /home/runner/work/breeze:/data1/resource/breeze  --net="host"  --name breeze_github_ci ficohu/breeze:githubci003
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: check vintage
        run: |
          docker ps -a
          curl http://127.0.0.1:8080/config/cloud/redis/testbreeze/redismeshtest
      - name: Create Socks
        run: |
          ps -aux|grep breeze
          mkdir -p /home/runner/work/breeze/logs
          mkdir -p /home/runner/work/breeze/snapshot
          mkdir -p /home/runner/work/breeze/socks
          touch /home/runner/work/breeze/socks/config+cloud+redis+testbreeze+redismeshtest@redis:56810@rs
          ls -all /home/runner/work/breeze/snapshot
          ls -all /home/runner/work/breeze/socks
          ls -all /home/runner/work/breeze/logs
      - name: Run
        run: nohup cargo run -- --discovery vintage://127.0.0.1:8080 --snapshot /home/runner/work/breeze/snapshot --service-path /home/runner/work/breeze/socks --log-dir /home/runner/work/breeze/logs --upgrade --port 9984 --metrics-probe 10.10.10.10:53 --log-level info  > /home/runner/work/breeze/logs/log.file  2>&1 &
      - name: Build Again
        run: cargo build --verbose
      - name: Check Port
        run: |
          netstat -nat|grep LISTEN
          ps -aux|grep breeze
          ls -all /home/runner/work/breeze/snapshot
          ls -all /home/runner/work/breeze/socks
          ls -all /home/runner/work/breeze/logs
          cat /home/runner/work/breeze/logs/breeze.log
          cat /home/runner/work/breeze/logs/log.file
      - name: Run tests
        run: cargo test --verbose
      - name: Check Port
        run: |
          netstat -nat|grep LISTEN
          ps -aux|grep breeze
          ls -all /home/runner/work/breeze/snapshot
          ls -all /home/runner/work/breeze/socks
          ls -all /home/runner/work/breeze/logs
          cat /home/runner/work/breeze/logs/breeze.log
          cat /home/runner/work/breeze/logs/log.file
