[package]
name = "net"
version = "0.1.0"
authors = ["icy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.15.0"
async-trait = "0.1.51"
