[package]
name = "metrics"
version = "0.1.0"
authors = ["mingzhe10 <mingzhe10@staff.weibo.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds = { path = "../ds" }

once_cell = "1.8.0"
local-ip-address = "0.4.2"
tokio = "1.13.0"
lazy_static = "1.4.0"
futures = "0.3.16"
log = "0.4.14"
psutil = "3.2.1"
